title: 'ANSYS Workbench'
compute:
  - name: 'ANSYS Workbench 15.0.7 (Software Rendering)'
    batch: 'oakley'
    node:
      - type: 'any'
        ppn: 12
        desc: >
          Choose any type of compute node. This reduces the wait time
          as there are no node specific requirements.
      - type: 'bigmem'
        ppn: 12
        desc: >
          This node has 192GB of available RAM. There are only 8 of
          these nodes on Oakley.
      - type: 'hugemem'
        ppn: 32
        desc: >
          This node has 1TB of available RAM as well as 32 cores.
          There is only 1 of these nodes on Oakley. A reservation may
          be required to use this node.
    pbs:
      envvars:
        ANSYS_MODULE: 'ansys/15.0.7'
        GPU_OFF: '1'
  - name: 'ANSYS Workbench 15.0.7 (Hardware Rendering)'
    batch: 'oakley'
    node:
      - &oak_vis
        type: 'vis'
        ppn: 12
        desc: >
          This node may come with 1 to 2 Nvidia GPUs. Allows for 3D
          visualization software to run as well as CUDA computations.
    pbs:
      envvars:
        ANSYS_MODULE: 'ansys/15.0.7'
